package imagetrack.app.lanuguages

import java.util.ArrayList

object LanguageArray {

    fun arrayValues(): ArrayList<LanguageSupportModel> {
        val languageSupportModels: ArrayList<LanguageSupportModel> = ArrayList()
        languageSupportModels.add(LanguageSupportModel("Afrikaans", "af", "No"))
        languageSupportModels.add(LanguageSupportModel("Albanian", "sq", "No"))
        languageSupportModels.add(LanguageSupportModel("Amharic", "am", "No"))
        languageSupportModels.add(LanguageSupportModel("Arabic", "ar", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Armenian", "hy", "No"))
        languageSupportModels.add(LanguageSupportModel("Azerbaijani", "az", "No"))
        languageSupportModels.add(LanguageSupportModel("Basque", "eu", "No"))
        languageSupportModels.add(LanguageSupportModel("Belarusian", "be", "No"))
        languageSupportModels.add(LanguageSupportModel("Bengali", "bn", "No"))
        languageSupportModels.add(LanguageSupportModel("Bosnian", "bs", "No"))
        languageSupportModels.add(LanguageSupportModel("Catalan", "ca", "No"))
        languageSupportModels.add(LanguageSupportModel("Cebuano", "ceb", "No"))
        languageSupportModels.add(LanguageSupportModel("Chinese (Simplified)", "zh-CN", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Chinese (Traditional) ", "zh-TW", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Corsican ", "co", "No"))
        languageSupportModels.add(LanguageSupportModel("Croatian", "hr", "No"))
        languageSupportModels.add(LanguageSupportModel("Czech", "cs", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Danish", "da", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Dutch", "nl", "Yes"))
        languageSupportModels.add(LanguageSupportModel("English", "en", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Esperanto", "eo", "No"))
        languageSupportModels.add(LanguageSupportModel("Estonian", "et", "No"))
        languageSupportModels.add(LanguageSupportModel("Finnish", "fi", "Yes"))
        languageSupportModels.add(LanguageSupportModel("French", "fr", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Frisian", "fy", "No"))
        languageSupportModels.add(LanguageSupportModel("Galician", "gl", "No"))
        languageSupportModels.add(LanguageSupportModel("Georgian", "ka", "No"))
        languageSupportModels.add(LanguageSupportModel("German", "de", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Greek", "el", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Gujarati", "gu", "No"))
        languageSupportModels.add(LanguageSupportModel("Haitian Creole", "ht", "No"))
        languageSupportModels.add(LanguageSupportModel("Hausa", "ha", "No"))
        languageSupportModels.add(LanguageSupportModel("Hawaiian", "haw", "No"))
        languageSupportModels.add(LanguageSupportModel("Hebrew", "he", "No"))
        languageSupportModels.add(LanguageSupportModel("Hindi", "hi", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Hmong", "hmn", "No"))
        languageSupportModels.add(LanguageSupportModel("Hungarian", "hu", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Icelandic", "is", "No"))
        languageSupportModels.add(LanguageSupportModel("Igbo", "ig", "No"))
        languageSupportModels.add(LanguageSupportModel("Indonesian", "id", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Irish", "ga", "No"))
        languageSupportModels.add(LanguageSupportModel("Italian", "it", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Japanese", "ja", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Javanese", "jv", "No"))
        languageSupportModels.add(LanguageSupportModel("Kannada", "kn", "No"))
        languageSupportModels.add(LanguageSupportModel("Kazakh", "kk", "No"))
        languageSupportModels.add(LanguageSupportModel("Khmer", "km", "No"))
        languageSupportModels.add(LanguageSupportModel("Korean", "ko", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Kurdish", "ku", "No"))
        languageSupportModels.add(LanguageSupportModel("Kyrgyz", "ky", "No"))
        languageSupportModels.add(LanguageSupportModel("Lao", "lo", "No"))
        languageSupportModels.add(LanguageSupportModel("Latin", "la", "No"))
        languageSupportModels.add(LanguageSupportModel("Latvian", "lv", "No"))
        languageSupportModels.add(LanguageSupportModel("Lithuanian", "lt", "No"))
        languageSupportModels.add(LanguageSupportModel("Luxembourgish", "lb", "No"))
        languageSupportModels.add(LanguageSupportModel("Macedonian", "mk", "No"))
        languageSupportModels.add(LanguageSupportModel("Malagasy", "mg", "No"))
        languageSupportModels.add(LanguageSupportModel("Malay", "ms", "No"))
        languageSupportModels.add(LanguageSupportModel("Malayalam", "ml", "No"))
        languageSupportModels.add(LanguageSupportModel("Maltese", "mt", "No"))
        languageSupportModels.add(LanguageSupportModel("Maori", "mi", "No"))
        languageSupportModels.add(LanguageSupportModel("Marathi", "mr", "No"))
        languageSupportModels.add(LanguageSupportModel("Mongolian", "mn", "No"))
        languageSupportModels.add(LanguageSupportModel("Myanmar (Burmese)", "my", "No"))
        languageSupportModels.add(LanguageSupportModel("Nepali", "ne", "No"))
        languageSupportModels.add(LanguageSupportModel("Norwegian", "no", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Nyanja (Chichewa)", "ny", "No"))
        languageSupportModels.add(LanguageSupportModel("Pashto", "ps", "No"))
        languageSupportModels.add(LanguageSupportModel("Persian", "fa", "No"))
        languageSupportModels.add(LanguageSupportModel("Polish", "pl", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Portuguese ", "pt", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Punjabi", "pa", "No"))
        languageSupportModels.add(LanguageSupportModel("Romanian", "ro", "No"))
        languageSupportModels.add(LanguageSupportModel("Russian", "ru", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Samoan", "sm", "No"))
        languageSupportModels.add(LanguageSupportModel("Scots Gaelic", "gd", "No"))
        languageSupportModels.add(LanguageSupportModel("Serbian", "sr", "No"))
        languageSupportModels.add(LanguageSupportModel("Sesotho", "st", "No"))
        languageSupportModels.add(LanguageSupportModel("Shona ", "sn", "No"))
        languageSupportModels.add(LanguageSupportModel("Sindhi", "sd", "No"))
        languageSupportModels.add(LanguageSupportModel("Sinhala (Sinhalese)", "si", "No"))
        languageSupportModels.add(LanguageSupportModel("Slovak", "sk", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Slovenian", "sl", "No"))
        languageSupportModels.add(LanguageSupportModel("Somali", "so", "No"))
        languageSupportModels.add(LanguageSupportModel("Spanish", "es", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Sundanese", "su", "No"))
        languageSupportModels.add(LanguageSupportModel("Swahili", "sw", "No"))
        languageSupportModels.add(LanguageSupportModel("Swedish", "sv", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Tagalog (Filipino)", "tl", "No"))
        languageSupportModels.add(LanguageSupportModel("Tajik", "tg", "No"))
        languageSupportModels.add(LanguageSupportModel("Tamil", "ta", "No"))
        languageSupportModels.add(LanguageSupportModel("Telugu", "te", "No"))
        languageSupportModels.add(LanguageSupportModel("Thai", "th", "No"))
        languageSupportModels.add(LanguageSupportModel("Turkish", "tr", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Ukrainian", "uk", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Urdu", "ur", "No"))
        languageSupportModels.add(LanguageSupportModel("Uzbek", "uz", "No"))
        languageSupportModels.add(LanguageSupportModel("Vietnamese", "vi", "Yes"))
        languageSupportModels.add(LanguageSupportModel("Welsh", "cy", "No"))
        languageSupportModels.add(LanguageSupportModel("Xhosa ", "xh", "No"))
        languageSupportModels.add(LanguageSupportModel("Yiddish", "yi", "No"))
        languageSupportModels.add(LanguageSupportModel("Yoruba", "yo", "No"))
        languageSupportModels.add(LanguageSupportModel("Zulu", "zu", "No"))
        return languageSupportModels
    }


}